name: calendar_view_widget
description: Calendar and events view widget for Flutter.
version: 0.2.5
homepage: https://github.com/crimercbddev/calendar_view_widget

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  quiver:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
